apiVersion: v1
kind: Service
metadata:
  name: testtaxiapp-service
spec:
  type: NodePort
  selector:
    app: testtaxi-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
---
apiVersion: v1
kind: Pod
metadata:
  name: testtaxiapp-pod
  labels:
    app: testtaxi-app
spec:
  containers:
  - name: testtaxiapp-container
    image: sreemanthena/taxicodecontainer:1.0
    ports:
    - containerPort: 80
