apiVersion: v1
kind: Service
metadata:
  name: taxiapp-service
spec:
  type: NodePort
  selector:
    app: taxi-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
---
apiVersion: v1
kind: Pod
metadata:
  name: taxiapp-pod
  labels:
    app: taxi-app
spec:
  containers:
  - name: taxiapp-container
    image: sreemanthena/taxicodecontainer:1.0
    ports:
    - containerPort: 80
